kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: element-web-anyuid
subjects:
  - kind: ServiceAccount
    name: matrix-element-element-web
    namespace: matrix-element
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: 'system:openshift:scc:anyuid'
