apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: matrix-postgresql
  namespace: openshift-gitops
spec:
  destination:
    namespace: matrix-postgresql
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: postgresql
    repoURL: https://github.com/vrutkovs/synapse-operatefirst
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
