apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: matrix-sealed-secrets
  namespace: openshift-gitops
spec:
  destination:
    namespace: matrix-sealed-secrets
    server: https://kubernetes.default.svc
  project: default
  source:
    path: sealed-secrets
    repoURL: https://github.com/vrutkovs/synapse-operatefirst
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
