apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: matrix-synapse
spec:
  encryptedData:
    auth.yaml: AgBkD5uNagM1Pqr3MXWjxpdYWCeY+32i+RtWkIl1zGTFbFKbhifqXSIFkJW86GL5RYR2Up6WK91PfUYPhmHFrhElSpZhh5jgIT34/wuF1L+GVhTEkBVyzxrdosWc6ocotrKc2qLc6ES2vl8T2w7Jl6SLZfjT+WriSd3EHv+n0mxpR1zYfTwk/ZlI+jiimLQRKfZzBFssz6OgKjPwbthp9UklE8fD5tOpU/c14MHHPbeDn3ChrxkYt8RsmRevytTmMGGOg6bmQOIo28yzKnb6Xc8CFvgKSxSIU2E564A5eI/yCsd2EXKcdm1anmQoF92E7Emi/xE/Zll1YUw/iLlBxr5dxWMeT+opHZvtG9uUYkCUOzg2nQpdDiJAv74opYTSidwLWKpA8u6HMcnE19aCjwAFgNzndPhYicDn6bzBD9P6h41KPEBtY1EpeRhch0IyiOHcavdNMk4YQxE2jwZZTXYiOOkOaml3ujg5XJMt6CNvQcuQajEYXi55UdUA83AUhLOUHLCpOxo8kQieCMMSuqWHcQ7+N90I7QQqHMXLgZAX1Iv3smpnIW6S/RImj7Pkch3D7OcgWEQY/lf+T1WBFOEAZi1PTIQOZRe33HzE9qH5FkZsH3y6AtJCebf0ayWg19wQcCs52DfX/VbinFVAYvJwz3Z7EUXOnwQcvAMIgT0KxaQ+vUoM2UVqXK6YVovChnZEuHFPIy3NLkjBhHUQfZ6Ygj8gJcvQymwPHlB8XXiiiemGxxPZ6Grh2C0F+Juf6UmQ77oKSstM8PC+GXFbMMeBK1d0JK/+kMF6Ull3N4+3meKuYHj1qXXFxg6PxJ6fzEgQ5EyrR9Xo1i1bwf1IoNai6Gpgm3giseExdRsovrdbkC0ePKBtZG9gmtji1yz4VKm37ppxlmfJ2GKpqjUlMjTlnO+VgMPiztxIaUNu6FHtlycUCaVZEZo40LnzIznm5zq+ttY0DkB4QGStQTRIcY2+/7I2BqtnJOpeyTq2ujc1U/la9dFFSDs2p9cLSq4Srtma98MHcEgsv18j6jCZKfMAM483TiO5TNdFnQkmcUWuiBway7BLrVG4BQX9iWVY7+4pVHClvaozyFW9S63FtAQV0F/dVndHmoIyzMjcX4wntpdRaTnpUxQdsJSqxXF8bmu2WC6kgI5Hdzvpo6tRmxDreUwdq5ZoL1rV3Gog7pyS56NZNhQJ6FLarGyBTuV1Xlec6yvk2k1s+zwmYNbC88NeJovdyiO5u+GFSttDTtxgaoTU7mvsxVPZTCYiEHNVIL4roWF+vecpHwPmjCESlu1xIdpl/UAaeCCvERYqrLCPOG5qTjRSUsegAngR4II/5X6INH2a3gW2wmtuTACzWRcwzXfsuBIF9IPIgnrX+oHULRONmhhuoDZy84YhBNoDNBXeR/Fpi5vMxBJh9MdOuuExie9BTgmZiIWhva3/Gj9RjXE94VTnfF4EEiUYnqKMYhwB829qpV6EBIOAXuGNd09xmJ3SYy6OQLT17v47jUKXGzy2l6NuPw5mBm3Q1YPCVpGjCnOKjR4VsLHHMkNn7T8/uvwF/vUMTFINCA==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
        sealedsecrets.bitnami.com/managed: "true"
      creationTimestamp: null
      name: matrix-synapse

