apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: matrix-synapse-signingkey
spec:
  encryptedData:
    signing.key: AgBuIxIQkQBstf0wkCJNlk8gM/YBfSRz+Jciyo39o9OalguQlpcu+aCeefxjdEOZjzFbcSFRKEP94IoEgo7owryRvJ+wMriUpm019AoeAuriXdKhXWeShJFlX8C1LW7V9+AQ7KMoH7s7XugZY2pSC2VhyABGHgU0/46y+jAncA7WQ6ldIh9Q6A11dycO/3OhC3PYdE36rZ3cQQeFqrMrLlmDO2ippfDmRIO6hdfDMVBxIPTPGSEh0YPhLbCqMUhRxAOMcKTbSrRZc6m2SmYCwiHyj1N4WuNpQCgGIgjhiIaVYhWGNQkXiFfCbFPbTtb6rz5cAq2vjVSahq766P2UIt1c4CY1njEg+cadLiaqjY5JAHzXf/Zv3VA3JoHglA/QPIXoO3MSz0ld0IUcP2oynKjW47EA4BvSrHa6IqpYPaKYLwh7IAmG4K9Jva00puYIbXJL0ZHcaM6mCxKGab/eM5bVwzIsGpN3TLkD8BBk/KlRVZMnLcxNHy0wt9h9yD+Agdv1/rhUjZFSZjtaJQJVAaiSmQKPDhIa9MCZSd4sZwl1AQyX+9nEdjcjrB/ZuMQnqmSb6d+2theHtjuYE5nh+xa2rZoxbTK9+5RJr7QS65hHuSa9MwC6rSaoYLB3WknKRs8H4YG4CyRPeFzfKK5BmcCSMngWd2DB5732fRsIWHs2FSCcoorTxmp9ez/mCbuRjE1kr40/gqYIkqhbl73tQ55ortlotbA5v8P2GixCBWmXCc6eJhP1XNbcICmeZWP5/9zfD9et0J1yLcyWYg==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: matrix-synapse-signingkey
    type: Opaque

