apiVersion: v1
kind: Service
metadata:
  name: slack-bridge-service
spec:
  selector:
    app: slack-bridge
  ports:
    - name: slack-port
      port: 9805
      targetPort: 9805
    - name: matrix-port
      port: 5858
      targetPort: 5858
